# temporary storage
tmpdir: '/scratch'

#demux
barcodes: 'workflow/barcodes/Sequel_96_barcodes_v1.IDT_pad.fasta'

# Targets
beds:
    targets: 'workflow/targets/PacBio-PGx_genes_hg38_target.bed'
    probes: 'workflow/targets/PacBio-full_opt_design_p1X_hg38_TE-97333771_probe_gene_names.bed'
    exons: 'workflow/targets/Exons_coding_refseq_named.bed'

# deepvariant
DEEPVARIANT_VERSION: '1.3.0-gpu'  # GPU
N_SHARDS: 256

ref:
  shortname: 'GRCh38_noalt'
  fasta: 'reference/human_GRCh38_no_alt_analysis_set.fasta'
  index: 'reference/human_GRCh38_no_alt_analysis_set.fasta.fai'
  chr_lengths: 'reference/human_GRCh38_no_alt_analysis_set.chr_lengths.txt'  # cut -f1,2 reference.fasta.fa > reference.chr_lengths.txt
  tr_bed: 'workflow/targets/tandem_repeats.bed'

# extra
QC:
    runQC: True
    lowcov: 7
