# temporary storage
tmpdir: '/scratch'

#demux
barcodes: 'workflow/barcodes/Sequel_96_barcodes_v1.IDT_pad.fasta'

# Targets
beds:
    targets: 'workflow/targets/brca/target_regions.bed'
    probes: 'workflow/targets/brca/Probes_merged_ok_PacBio_BRCA1_2_TE-92415932_LongRead_p1X_hg38_220105185650.bed'
    exons: 'workflow/targets/brca/brca_exons.bed'
merge: 1000000

# deepvariant
DEEPVARIANT_VERSION: '1.3.0-gpu'  # GPU
N_SHARDS: 96

ref:
  shortname: 'GRCh38_noalt'
  fasta: 'reference/human_GRCh38_no_alt_analysis_set.fasta'
  index: 'reference/human_GRCh38_no_alt_analysis_set.fasta.fai'
  chr_lengths: 'reference/human_GRCh38_no_alt_analysis_set.chr_lengths.txt'  # cut -f1,2 reference.fasta.fa > reference.chr_lengths.txt
  tr_bed: 'workflow/targets/tandem_repeats.bed'

# glnexus
GLNEXUS_VERSION: 'v1.4.1'

# extra
QC:
    runQC: True
    lowcov: 7
picard:
  near_distance: 10000
  sample_size: 1000
