# temporary storage
tmpdir: '/scratch'

#demux
barcodes: 'workflow/barcodes/Sequel_96_barcodes_v1.IDT_pad.fasta'

# Targets
beds:
    targets: 'workflow/targets/stanford_idt/ontarget_IDT_Stanford.bed'
    probes: 'workflow/targets/stanford_idt/03656111_Pac3Kb_0.1x_v4_probe.bed'
    exons: 'workflow/targets/stanford_idt/ontarget_exons.bed'
merge: 1000000

# deepvariant
DEEPVARIANT_VERSION: '1.3.0-gpu'  # GPU
N_SHARDS: 256

ref:
  shortname: 'GRCh38_noalt'
  fasta: 'reference/human_GRCh38_no_alt_analysis_set.fasta'
  index: 'reference/human_GRCh38_no_alt_analysis_set.fasta.fai'
  chr_lengths: 'reference/human_GRCh38_no_alt_analysis_set.chr_lengths.txt'  # cut -f1,2 reference.fasta.fa > reference.chr_lengths.txt
  tr_bed: 'workflow/targets/tandem_repeats.bed'

# glnexus
GLNEXUS_VERSION: 'v1.4.1'

# extra
QC:
    runQC: True
    lowcov: 7
